// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcT6ZCsAjOxe-ddWqAtvLRHA9lkXs9NFQ',
    appId: '1:289105318442:web:76ea05e446e52e381da953',
    messagingSenderId: '289105318442',
    projectId: 'classwork8-43801',
    authDomain: 'classwork8-43801.firebaseapp.com',
    storageBucket: 'classwork8-43801.firebasestorage.app',
    measurementId: 'G-6DBYLE7DNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpHP808jUX0qIsGNaXOYn1ppylrGUkOvw',
    appId: '1:289105318442:android:aaccf39b2619a0341da953',
    messagingSenderId: '289105318442',
    projectId: 'classwork8-43801',
    storageBucket: 'classwork8-43801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYqXJxJz8RSuuuR6PwbtIG3h9JTIsbCX4',
    appId: '1:289105318442:ios:ccbe36e525254e6e1da953',
    messagingSenderId: '289105318442',
    projectId: 'classwork8-43801',
    storageBucket: 'classwork8-43801.firebasestorage.app',
    iosBundleId: 'com.example.cw8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYqXJxJz8RSuuuR6PwbtIG3h9JTIsbCX4',
    appId: '1:289105318442:ios:ccbe36e525254e6e1da953',
    messagingSenderId: '289105318442',
    projectId: 'classwork8-43801',
    storageBucket: 'classwork8-43801.firebasestorage.app',
    iosBundleId: 'com.example.cw8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcT6ZCsAjOxe-ddWqAtvLRHA9lkXs9NFQ',
    appId: '1:289105318442:web:3ba1c84d95b1362d1da953',
    messagingSenderId: '289105318442',
    projectId: 'classwork8-43801',
    authDomain: 'classwork8-43801.firebaseapp.com',
    storageBucket: 'classwork8-43801.firebasestorage.app',
    measurementId: 'G-95ZLG0B2TX',
  );
}
